export interface Theme {
  id: string;
  name: string;
  category:
    | "movies"
    | "anime"
    | "games"
    | "startups"
    | "tech"
    | "os"
    | "events"
    | "community"
    | "default"
    | "india"
    | "festival"
    | "season"
    | "japan"
    | "nature";
  description: string;
  tokens: {
    background: string;
    surface: string;
    foreground: string;
    muted: string;
    primary: string;
    primaryForeground: string;
    accent: string;
    border: string;
    fontDisplay: string;
    fontBody: string;
    radius: string;
    backgroundImage?: string;
  };
}

export const STARTER_THEMES: Theme[] = [
  {
    id: "crimson-default",
    name: "FormStack Crimson",
    category: "default",
    description: "The signature black-and-white theme with a crimson accent.",
    tokens: {
      background: "#FFFFFF",
      surface: "#FAFAFA",
      foreground: "#0A0A0A",
      muted: "#737373",
      primary: "#D7263D",
      primaryForeground: "#FFFFFF",
      accent: "#0A0A0A",
      border: "#E5E5E5",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.75rem",
    },
  },
  {
    id: "midnight-cinema",
    name: "Midnight Cinema",
    category: "movies",
    description: "Inspired by indie film posters — deep black with film-red accents.",
    tokens: {
      background: "#0B0B0F",
      surface: "#15151C",
      foreground: "#F5F5F5",
      muted: "#8A8A95",
      primary: "#E50914",
      primaryForeground: "#FFFFFF",
      accent: "#FFD166",
      border: "#26262E",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.5rem",
    },
  },
  {
    id: "shonen-sunrise",
    name: "Shonen Sunrise",
    category: "anime",
    description: "Saturday-morning anime energy — orange, indigo, exclamation marks optional.",
    tokens: {
      background: "#FFF7ED",
      surface: "#FFFFFF",
      foreground: "#1E1B4B",
      muted: "#6B7280",
      primary: "#F97316",
      primaryForeground: "#FFFFFF",
      accent: "#4F46E5",
      border: "#FED7AA",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "1rem",
    },
  },
  {
    id: "arcade-neon",
    name: "Arcade Neon",
    category: "games",
    description: "CRT glow and 80s arcade colors.",
    tokens: {
      background: "#0F0524",
      surface: "#1A0B3D",
      foreground: "#E0E7FF",
      muted: "#A78BFA",
      primary: "#22D3EE",
      primaryForeground: "#0F0524",
      accent: "#F472B6",
      border: "#3730A3",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.25rem",
    },
  },
  {
    id: "yc-startup",
    name: "YC Orange",
    category: "startups",
    description: "Clean, fundraising-deck minimalism with a bright orange CTA.",
    tokens: {
      background: "#FFFFFF",
      surface: "#F8FAFC",
      foreground: "#0F172A",
      muted: "#64748B",
      primary: "#F26625",
      primaryForeground: "#FFFFFF",
      accent: "#0F172A",
      border: "#E2E8F0",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.5rem",
    },
  },
  {
    id: "terminal-os",
    name: "Terminal OS",
    category: "os",
    description: "Green-on-black like a 1980s mainframe terminal. Yes, you can hack the planet.",
    tokens: {
      background: "#000000",
      surface: "#0A0F0A",
      foreground: "#39FF14",
      muted: "#4ADE80",
      primary: "#39FF14",
      primaryForeground: "#000000",
      accent: "#FACC15",
      border: "#14532D",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0rem",
    },
  },
  {
    id: "devcon-event",
    name: "DevCon",
    category: "events",
    description: "Conference-badge vibes — bright, friendly, ships with a lanyard.",
    tokens: {
      background: "#F5F3FF",
      surface: "#FFFFFF",
      foreground: "#1E1B4B",
      muted: "#6D28D9",
      primary: "#7C3AED",
      primaryForeground: "#FFFFFF",
      accent: "#F472B6",
      border: "#DDD6FE",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.75rem",
    },
  },
  {
    id: "mumbai-monsoon",
    name: "Mumbai Monsoon",
    category: "india",
    description: "Rainy-season grey skies, wet tarmac, and the warm orange of taxi roofs.",
    tokens: {
      background: "#1B2430",
      surface: "#222C3A",
      foreground: "#E6E9EF",
      muted: "#7B8A9D",
      primary: "#F58A1F",
      primaryForeground: "#1B2430",
      accent: "#5DC8E8",
      border: "#2C3849",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.5rem",
    },
  },
  {
    id: "jaipur-pink",
    name: "Jaipur Pink City",
    category: "india",
    description: "Hawa Mahal sandstone, royal pinks and dusty desert ochre.",
    tokens: {
      background: "#FFF1E6",
      surface: "#FFE3D1",
      foreground: "#5B1A2E",
      muted: "#A8617A",
      primary: "#D63384",
      primaryForeground: "#FFFFFF",
      accent: "#E89B3F",
      border: "#F4C2A1",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "1rem",
    },
  },
  {
    id: "kerala-backwaters",
    name: "Kerala Backwaters",
    category: "india",
    description: "Coconut palms, slow rivers, and a green so saturated it hums.",
    tokens: {
      background: "#F0F7F1",
      surface: "#FFFFFF",
      foreground: "#0D3B2E",
      muted: "#4F7B6A",
      primary: "#0B7B5E",
      primaryForeground: "#FFFFFF",
      accent: "#E2B23A",
      border: "#CFE0D5",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.75rem",
    },
  },
  {
    id: "diwali-festival",
    name: "Diwali Festival",
    category: "festival",
    description: "Diya gold, marigold, and the deep purple of a festival night.",
    tokens: {
      background: "#1A0B2E",
      surface: "#241341",
      foreground: "#FFE9B3",
      muted: "#B79DD9",
      primary: "#F2B134",
      primaryForeground: "#1A0B2E",
      accent: "#E84A5F",
      border: "#3A2358",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.875rem",
    },
  },
  {
    id: "holi-festival",
    name: "Holi Colours",
    category: "festival",
    description: "Throw-the-rulebook bright pinks, yellows, greens. Spring in a form.",
    tokens: {
      background: "#FFFCF5",
      surface: "#FFFFFF",
      foreground: "#1F1147",
      muted: "#6B5BA8",
      primary: "#E84A8C",
      primaryForeground: "#FFFFFF",
      accent: "#3CC2A4",
      border: "#FCE3E9",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "1.25rem",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    category: "japan",
    description: "Shibuya neon on rainy pavement. Magenta, indigo, electric blue.",
    tokens: {
      background: "#0F0A1E",
      surface: "#1A1330",
      foreground: "#E2DCFF",
      muted: "#8079B8",
      primary: "#FF2D95",
      primaryForeground: "#FFFFFF",
      accent: "#5AC8FA",
      border: "#2B2150",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.5rem",
    },
  },
  {
    id: "kyoto-sakura",
    name: "Kyoto Sakura",
    category: "japan",
    description: "Soft cherry blossoms, washi paper, temple greys. Quiet and considered.",
    tokens: {
      background: "#FFF7F8",
      surface: "#FFFFFF",
      foreground: "#2D2233",
      muted: "#9C8A95",
      primary: "#E68AA8",
      primaryForeground: "#FFFFFF",
      accent: "#A8C8A0",
      border: "#F5DCE2",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.625rem",
    },
  },
  {
    id: "windows-95",
    name: "Windows ‘95",
    category: "os",
    description: "Teal desktop, beige chrome, Tahoma vibes. Pure nostalgia.",
    tokens: {
      background: "#008080",
      surface: "#C0C0C0",
      foreground: "#000000",
      muted: "#4D4D4D",
      primary: "#000080",
      primaryForeground: "#FFFFFF",
      accent: "#FFFF00",
      border: "#808080",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0rem",
    },
  },
  {
    id: "windows-xp",
    name: "Windows XP",
    category: "os",
    description: "Bliss-wallpaper green hills, Luna blue, that classic Start-button gradient.",
    tokens: {
      background: "#E6F3FF",
      surface: "#FFFFFF",
      foreground: "#003399",
      muted: "#6B7A99",
      primary: "#0058E1",
      primaryForeground: "#FFFFFF",
      accent: "#7FBA00",
      border: "#B8D5F0",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.5rem",
    },
  },
  {
    id: "forest-deep",
    name: "Deep Forest",
    category: "nature",
    description: "Moss, ferns, dappled light. Calm, considered, organic.",
    tokens: {
      background: "#0E1A14",
      surface: "#16261D",
      foreground: "#E3EBDA",
      muted: "#7E9683",
      primary: "#7CB342",
      primaryForeground: "#0E1A14",
      accent: "#D4A24C",
      border: "#23362A",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.875rem",
    },
  },
  {
    id: "autumn-leaves",
    name: "Autumn Leaves",
    category: "season",
    description: "Maple, copper, cinnamon. Cardigan-weather forms.",
    tokens: {
      background: "#FBF3E8",
      surface: "#FFFFFF",
      foreground: "#3B1F0D",
      muted: "#8C6244",
      primary: "#C2410C",
      primaryForeground: "#FFFFFF",
      accent: "#CA8A04",
      border: "#EDD9B8",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.875rem",
    },
  },
  {
    id: "winter-frost",
    name: "Winter Frost",
    category: "season",
    description: "Icicle blues, soft snow, glacier blacks. Minimal, sharp, clean.",
    tokens: {
      background: "#F0F6FA",
      surface: "#FFFFFF",
      foreground: "#0B1F2E",
      muted: "#5B7A92",
      primary: "#0EA5E9",
      primaryForeground: "#FFFFFF",
      accent: "#94A3B8",
      border: "#D4E5F0",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
      radius: "0.5rem",
    },
  },
];

export const getTheme = (id: string): Theme =>
  STARTER_THEMES.find((t) => t.id === id) ?? STARTER_THEMES[0]!;
